<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<style>
body {
        font-family: 'Helvetica', serif;
        color: 303030;
    }
p {
    font-size:10px;
    }

.page-break {
    page-break-after: always;
}

.topo{
    font-family: 'Helvetica', serif;
    font-weight: bold;
    color: 303030;
    padding-top: 10px;
   
}

hr {
  margin: 40px 0;
}

h4{

    text-align: center;
}

.hr1 {
  width: 100%;
  margin-top: -100px;
  border: 0;
  border-top: 1px solid #CCC;
  text-align: center;
}

.assinatura{
    margin-top:20%;
    display: block;
    text-align: center;
}

.bloco{
    width:100%;
    display: block;
}
    .coluna_esquerda {
        
        display: block;
        font-size: 10px;
        width: 48%;
        float: left;
        position: absolute;
    }
    .coluna_direita {
        
        display: block;
        float: right;
        font-size: 10px;
        width: 48%;
        position: absolute;
    }

    span{
    font-size: 8px;
    color: #979797;
}
    th, td {
        border: 1px solid #dcdcdc;
        border-radius: 9px;
        padding:14px;
        font-size: 12px;
        text-transform: uppercase;
    }

    img{
        width: auto;
        height: 125px;
    }
</style>
<body>
<img src="img\sat_logo.png">
<h4>CONTRATO DE PRESTAÇÃO DE SERVIÇOS DE RASTREAMENTO COM COMODATO DE EQUIPAMENTO(S) RASTREADOR(ES)</h4>
<p>DE UM LADO, SAT TELECOM SEVERINO JUNIOR MONTEIRO, NOME FANTASIA + LOCALIZA SAT ;EMPRESA ESTABELECIDA NA
RUA EPITÁCIO PESSOA, 13, SALA 02 - 1º ANDAR, CENTRO - AROEIRAS - PB INSCRITA NO CNPJ SOB O N° 15.389.818/0001-15
DORAVANTE DESIGNADA CONTRATADA, E DE OUTRO LADO, EMPRESA OU PESSOA FÍSICA A SEGUIR QUALIFICADA:
</p>
<h5>DADOS DO CLIENTE</h5>
<table style="width:100%">
  <tr>
    <td><span>NOME:</span> {{$data->nome}}</td>
  </tr>
</table>
<table style="width:100%">
<tr>
    <td><span>CPF/CNPJ:</span> {{$data->cpfcnpj}}</td>
    <td><span>RG:</span> {{$data->rg}}</td>
  </tr>
</table>
<table style="width:100%">
<tr>
    <td><span>CEP:</span> {{$data->cep}}</td>
    <td><span>CIDADE:</span> {{$data->cidade}}</td>
    <td><span>ESTADO:</span> {{$data->rg}}</td>
</tr>
<tr>
    <td><span>RUA:</span> {{$data->rua}}</td>
    <td><span>BAIRRO:</span> {{$data->bairro}}</td>
    <td><span>NÚMERO:</span> {{$data->numero}}</td>
</tr>
</table>
<table style="width:100%">
  <tr>
    <td><span>COMPLEMENTO:</span> {{$data->complemento}}</td>
  </tr>
</table>
<table style="width:100%">
<tr>
    <td><span>EMAIL:</span> {{$data->email}}</td>
    <td><span>CELULAR:</span> {{$data->celular}}</td>
</tr>
</table>
<table style="width:100%">
<tr>
    <td><span>QTD. EQUIPAMENTOS:</span> {{$data->qtdequip}}</td>
    <td><span>MODELO:</span> {{$data->modelo}}</td>
    <td><span>IMEI:</span> {{$data->imei}}</td>
    <td><span>PLANO:</span> {{$data->plano}}</td>
</tr>
</table>
<table style="width:100%">
  <tr>
    <td><span>OBSERVAÇÕES:</span> {{$data->obs}}</td>
  </tr>
</table>
<h5>DADOS DO VEÍCULO</h5>
<table style="width:100%">
<tr>
    <td><span>MARCA:</span> {{$data->marca}}</td>
    <td><span>MODELO:</span> {{$data->model}}</td>
    <td><span>PLACA:</span> {{$data->placa}}</td>
</tr>
<tr>
    <td><span>COR:</span> {{$data->cor}}</td>
    <td><span>ANO:</span>{{$data->ano}}</td>
    <td><span>RENAVAM:</span>{{$data->renavam}}</td>
</tr>
</table>



<div class="page-break"></div>
<div class="bloco">
<div class="coluna_esquerda">
<div class="topo">1. O SERVIÇO DE RASTREAMENTO CONTRATADO CONSISTE EM:</div>
<div><b>A)</b> ARMAZENAMENTO, NO SERVIDOR DA CONTRATADA POR ATÉ 06 MESES (180 DIAS), DE
POSIÇÕES CAPTADAS VIA SATÉLITE E TRANSMITIDAS POR TELEFONIA CELULAR;</div>
<div class="topo">2. NÃO CABERÁ A CONTRATADA QUALQUER RESPONSABILIDADE POR:</div>
<div><b>A)</b> DANOS EMERGENTES E LUCROS CESSANTES DO CONTRATANTE FRUTO DA SUBTRAÇÃO
DA CARGA TRANSPORTADA, VEÍCULO, PASSAGEIROS, OBJETOS NO INTERIOR DO VEÍCULO,
PEÇAS E ACESSÓRIOS DO VEÍCULO;</div>
<div><b>B)</b> DANOS EMERGENTES OU LUCROS CESSANTES DO CONTRATANTE, CUJAS CAUSAS
POSSAM SER CORRELACIONADAS DIRETA OU INDIRETAMENTE À UTILIZAÇÃO OU
INTERRUPÇÃO DOS SERVIÇOS DE RASTREAMENTO, INOPERÂNCIA DO RASTREADOR OU
AGENDAMENTO DE SERVIÇO TÉCNICO EM HORÁRIO DISPONIBILIZADO PELA
CONTRATADA QUE NÃO SATISFAÇA A CONTRATANTE PARA EXECUÇÃO DE REPARO.</div>
<div><b>C)</b> DECORRÊNCIA DE ATOS DE TERCEIROS QUE NÃO SEJAM SEUS EMPREGADOS OU
PREPOSTOS.</div>
<div><b>D)</b> FALHAS NO FUNCIONAMENTO DO HARDWARE OU SOFTWARE DO RASTREADOR
EMBARCADO UTILIZADO PELA CONTRATANTE; FALHAS FRUTO DE: FALTA DE TELEFONIA
FIXA E INTERNET , FALHA NOS SINAIS DE SATÉLITE E TELEFONIA CELULAR QUE SÃO
SUJEITOS A INTERFERÊNCIAS EM ÁREAS COM OCORRÊNCIA DE ”SOMBRAS” PROJETADAS
POR EDIFÍCIOS, MONTANHAS E/OU OUTROS OBSTÁCULOS À PROPAGAÇÃO DAS ONDAS
EMANADAS DAS TORRES DE TRANSMISSÃO DA OPERADORA DE TELEFONIA, OU OUTRO
MEIO DE COMUNICAÇÃO UTILIZADO PELO PROVEDOR DA TECNOLOGIA DE
RASTREAMENTO; EM DECORRÊNCIA DE EVENTOS DA NATUREZA, TAIS COMO: RAIOS,
TEMPO NUBLADO, DESCARGAS ELÉTRICAS OU VENDAVAL OU ATO OU FATO DO HOMEM
QUE IMPLIQUE NA PERDA DE SINAL E CONSEQUENTE IMPOSSIBILIDADE DE
RASTREAMENTO EM VIRTUDE DESTES ACONTECIMENTOS, BEM COMO NA HIPÓTESE DE
CASO FORTUITO E OU FORÇA MAIOR. QUAISQUER TIPOS DE ACIDENTES OU DANOS AO
VEÍCULO E/OU TERCEIROS QUE VENHAM A SER PROVOCADOS PELO BLOQUEIO DO
VEÍCULO EM VIAS PÚBLICAS OU PRIVADAS.</div>
<div><b>E)</b> OMISSÃO OU NEGLIGÊNCIA DO CONTRATANTE DAS SUAS RESPONSABILIDADES.</div>
<div><b>F)</b> DANOS EMERGENTES OU LUCROS CESSANTES DO CONTRATANTE, POR PERDA DE
GARANTIA DO VEÍCULO DECORRENTE DA INSTALAÇÃO DO EQUIPAMENTO RASTREADOR.</div>
<div class="topo">3. OBRIGAÇÕES DA CONTRATANTE:</div>
<div><b>A)</b> A REALIZAÇÃO DE 01 (UM) TESTE DE POSIÇÃO E BLOQUEIO (SE CONTRATADO) MENSAL,
PARA VERIFICAR O FUNCIONAMENTO DO SISTEMA. AO VERIFICAR IRREGULARIDADE NA
POSIÇÃO GEOGRÁFICA OU AÇÃO DO BLOQUEIO (SE CONTRATADO) DEVERÁ SOLICITAR
REPARO A CONTRATADA.</div>
<div><b>B)</b> TODO E QUALQUER PROBLEMA OU ACIDENTE PROVENIENTE DO SERVIÇO SOLICITADO
PELO CONTRATANTE, SERÁ DE SUA INTEIRA RESPONSABILIDADE.</div>
<div><b>C)</b> EM CASO DE CONSTATAÇÃO DE DEFEITO DO RASTREADOR, O CONTRATANTE DEVERÁ
EXECUTAR OS SEGUINTES PROCEDIMENTOS:</div>
<div><b>C.1)</b> COMUNICAR A CONTRATADA O DEFEITO E SOLICITAR TESTES PARA DEPURAR O
PROBLEMA;</div>
<div><b>C.2)</b> SE CONFIRMADO O DEFEITO, O CONTRATANTE DEVERÁ ENCAMINHAR O
RASTREADOR OU O VEÍCULO AO POSTO MAIS PRÓXIMO CREDENCIADO PELA
CONTRATADA; OU EM COMUM ACORDO MANUTENIR O RASTREADOR NO MESMO LOCAL
QUE FOI REALIZADO A INSTALAÇÃO, PODENDO NESTE CASO SER COBRADO VALOR PARA
DESLOCAMENTO DO TÉCNICO AO LOCAL SOLICITADO PELO CONTRATANTE;</div>
<div><b>C.3)</b> PARA DEFEITOS QUE GERE A IMOBILIZAÇÃO DO VEÍCULO, O CONTRATANTE DEVERÁ
ENCAMINHAR O VEÍCULO PARA AUTO- ELÉTRICA MAIS PRÓXIMA E SOLICITAR A
DESATIVAÇÃO DO RASTREADOR INSTALADO. QUALQUER PROBLEMA COM RASTREADOR
QUE NÃO SEJA PROVENIENTE DE SUA FABRICAÇÃO, A MANUTENÇÃO NÃO SERÁ DE
RESPONSABILIDADE DA CONTRATADA , QUE CASO ACIONADA INDEVIDAMENTE SERÁ
COBRADA UMA TAXA DE MANUTENÇÃO.</div>
<div><b>D)</b> EM CASO DE VEÍCULO EM PERÍODO DE GARANTIA DO FABRICANTE, VERIFICAR SE A
INSTALAÇÃO DO RASTREADOR PODERÁ ACARRETAR A PERDA DA GARANTIA.</div>
</div>
<div class="coluna_direita">
<div class="topo">4. OBRIGAÇÕES DA CONTRATADA:</div>
<div><b>A)</b> SERVIÇOS DE MANUTENÇÃO SÓ SERÃO EXECUTADOS EM DIAS ÚTEIS, HORÁRIO
COMERCIAL E NO MESMO MUNICÍPIO DE DOMICÍLIO DECLARADO NESTE CONTRATO PELO
CONTRATANTE MEDIANTE AGENDAMENTO PRÉVIO.</div>
<div><b>B)</b> EM HAVENDO A OCORRÊNCIA DE SINISTRO, FALHA OPERACIONAL NÃO DECORRENTE
DA CLÁUSULA 2-D, E COMPROVADA OU ADMITIDA À CULPA DA CONTRATADA, AS PARTES
CONTRATANTES DO PRESENTE INSTRUMENTO CONCORDAM EXPRESSAMENTE QUE A
CONTRATADA RESSARCIRÁ À CONTRATANTE ATÉ A QUANTIA MÁXIMA DE 12 VEZES O
VALOR MENSAL EFETIVAMENTE COBRADO PELO SERVIÇO DE MONITORAMENTO
INDIVIDUAL DO VEÍCULO SINISTRADO, COMO VALOR MÁXIMO DE INDENIZAÇÃO EM
QUALQUER HIPÓTESE, MESMO QUE JUDICIAL.</div>

<div class="topo">5. SERVIÇOS ESPECIAIS:</div>
<div><b>A)</b> PEDIDO POR PARTE DO CONTRATANTE PARA REALIZAÇÃO DE TRANSFERÊNCIA DE
RASTREADOR DE UM PARA OUTRO VEÍCULO DE SUA PROPRIEDADE.</div>
<div><b>B)</b> AS TARIFAS SOBRE SERVIÇOS ESPECIAIS UTILIZADOS PELO CONTRATANTE SERÃO
COBRADAS NO ATO DA PRESTAÇÃO DO SERVIÇO E SERÃO DE INTEIRA E ÚNICA
RESPONSABILIDADE DO CONTRATANTE QUE DESDE JÁ DECLARA ESTAR CIENTE DE QUE A
UTILIZAÇÃO DE TAIS SERVIÇOS DEPENDE DE ÚNICA E EXCLUSIVAMENTE DE SUA VONTADE.</div>

<div class="topo">6. SERVIÇOS EXTRAS:</div>
<div><b>A)</b> NO CASO DE OCORRÊNCIA POLICIAL, O DEPARTAMENTO DE POLÍCIA DEVERÁ SER
ACIONADO DIRETAMENTE PELO CONTRATANTE. NO CASO DE REALIZAR O ACIONAMENTO
DESCRITO E PELA INDISPONIBILIDADE DAS AUTORIDADES E SERVIÇOS PÚBLICOS OU
PRIVADOS NÃO COMPARECEREM, A CONTRATADA NÃO PODERÁ SER RESPONSABILIZADA.</div>
<div><b>B)</b> O SERVIÇO DE PRONTA RESPOSTA (RESGATE DO VEÍCULO) É USADO PARA
OCORRÊNCIAS NO RIO E GRANDE RIO E É DE DECISÃO DA CONTRATANTE O EMPREGO OU
NÃO, SENDO O CUSTO DA OPERAÇÃO TOTALMENTE DA CONTRATANTE.</div>
<div><b>C)</b> O PORTAL DE INTERNET PARA ACESSAR POSIÇÕES DO VEÍCULO ATRAVÉS DE LOGIN E
SENHA FORNECIDOS PELA CONTRATADA.</div>
<div class="topo">7.VALOR E FORMA DE PAGAMENTO DOS SERVIÇOS:</div>
<div><b>A)</b> O PAGAMENTO REFERENTE AO SERVIÇO DE MONITORAMENTO SERÁ EFETUADO PELA
CONTRATANTE, MENSALMENTE NO DIA E VALOR CONTRATADO.</div>
<div><b>B)</b> CASO NÃO RECEBA O AVISO DE COBRANÇA DE MENSALIDADE, A CONTRATANTE SE
OBRIGA A COMUNICAR A CONTRATADA ATÉ 5 (CINCO) DIAS DO DIA DE VENCIMENTO,
PARA RECEBER INSTRUÇÕES PARA O RESPECTIVO PAGAMENTO.</div>
<div><b>C)</b> OS VALORES DAS MENSALIDADES SERÃO REAJUSTADOS ANUALMENTE, OU PELO
MENOR PERÍODO PERMITIDO PELA LEGISLAÇÃO VIGENTE, CONFORME VALOR DA
INFLAÇÃO ACUMULADA NOS ÚLTIMOS 12 MESES.</div>
<div><b>D)</b> O NÃO PAGAMENTO DAS OBRIGAÇÕES ASSUMIDAS PELA CONTRATANTE DOS SEUS
VENCIMENTOS OBRIGARÁ A CONTRATANTE AO PAGAMENTO DA PERMANÊNCIA DIÁRIA
DE 0,33% CONTADOS A PARTIR DA DATA DO VENCIMENTO ATÉ A DATA DO EFETIVO
PAGAMENTO, TENDO COMO BASE O ÍNDICE DE REAJUSTE DO IGPM OU CONFORME
ÍNDICE ECONÔMICO QUE VENHA A SUBSTITUÍ-LO, ACRESCIDO DE MULTA MORATÓRIA DE
2% (DOIS POR CENTO) SOBRE O VALOR PRINCIPAL CORRIGIDO.</div>
<div><b>E)</b> APÓS 10 DIAS EM ATRASO, A CONTRATADA SUSPENDERÁ OS SERVIÇOS ATÉ
REGULARIZAÇÃO DO PAGAMENTO E DESATIVAÇÃO DEFINITIVA APÓS 30 DIAS;</div>
<div><b>F)</b> A INADIMPLENCIA SUPERIOR A 30 DIAS ACARRETARÁ A CONTRATANTE A INCLUSÃO DE
SEU NOME JUNTO AOS ÓRGÃOS DE PROTEÇÃO AO CRÉDITO (SPC/SERASA);</div>
<div><b>G)</b> A CONTRATADA PODERÁ RESCINDIR, INDEPENDENTE DE QUALQUER COMUNICADO
FORMAL, A PARTIR DA INADIMPLÊNCIA DA 1ª MENSALIDADE. E AINDA, DEVIDO A
INADIMPLENCIA DO CONTRATANTE, FICA A CONTRATADA ISENTA POR QUAISQUER
RESPONSABILIDADES ORIUNDAS SUPERVENIENTES A PARTIR DESTE PRAZO.</div>
<div><b>H)</b> A CONTRATADA EXERCERÁ SEU DIREITO DE COBRANÇA DE TODO O DÉBITO GERADO
NO PERÍODO DE 60 (SESSENTA) DIAS EM INADIMPLÊNCIA, INCLUINDO: MULTA DIÁRIA,
MORA E JUROS LEGAIS, ALÉM DE EXERCER O DIREITO DE EXECUTAR O PROTESTO
LEGÍTIMO DE CRÉDITO, COBRANÇA JUDICIAL E HONORÁRIOS ADVOCATÍCIOS, NO
PATAMAR DE 20% SOBRE O TOTAL DA DÍVIDA.</div>
</div>
</div>
<div class="page-break"></div>

<div class="coluna_esquerda">
<div class="topo">8. A INSTALAÇÃO E MANUTENÇÃO DO RASTREADOR SERÁ DA SEGUINTE
FORMA:</div>
<div><b>A)</b> O CONTRATANTE ACEITA SUBMETER O SEU VEÍCULO A UMA INSPEÇÃO PRÉVIA,
ANTERIOR AO INÍCIO DOS SERVIÇOS DE INSTALAÇÃO, MANUTENÇÃO OU RETIRADA;
ASSINANDO JUNTAMENTE COM O INSTALADOR UM RELATÓRIO DESCRITIVO ONDE
DEVERÁ CONSTAR EXISTÊNCIA OU NÃO DE AVARIAS, RISCOS, AMASSADOS E OUTROS
DANOS. APÓS OS ENCERRAMENTOS DOS SERVIÇOS O CONTRATANTE CONCORDA EM
REALIZAR A CONSTATAÇÃO DO ESTADO GERAL DO VEÍCULO, FIRMANDO, JUNTAMENTE
COM REPRESENTANTE DA CONTRATADA, RELATÓRIO FINAL, APÓS O QUE NADA MAIS
PODERÁ RECLAMAR A TÍTULO DE INDENIZAÇÃO POR PROBLEMAS HAVIDOS DURANTE OS
MENCIONADOS SERVIÇOS.</div>
<div><b>B)</b> O RASTREADOR TEM GARANTIA DE FUNCIONAMENTO POR TODA VIGÊNCIA DESTE;</div>
<div><b>C)</b> A INSTALAÇÃO E USO DO RASTREADOR REDEVEICULOS.COM NÃO DANIFICAM PARTE
ELÉTRICA DO VEÍCULO, TÃO POUCO A PARTE AUTOMOTIVA. QUALQUER RECLAMAÇÃO
NESTE SENTIDO, OU SEJA, EVENTUAL PROBLEMA NO VEÍCULO QUE POSSA SER ATRIBUÍDO
À INSTALAÇÃO/USO DO APARELHO, DEVERÁ SER COMPROVADO ATRAVÉS DE TÉCNICOS
DA CONTRATADA OU QUEM ESTA INDICAR.</div>
<div><b>D)</b> NOS CHAMADOS PARA MANUTENÇÃO, QUANDO SE CONSTAR E SE FUNDAMENTAR
QUE O PROBLEMA NÃO FOI CAUSADO PELO NOSSO RASTREADOR OU OCORRER UMA
VISITA TÉCNICA EM QUE NÃO SEJA EXECUTADO O SERVIÇO POR FALTA DE DISPONIBILIDADE DO VEÍCULO
SERÁ COBRADO TAXA DE VISITA CONFORME “TABELA DE SERVIÇOS DA CONTRATADA”
EXISTENTE NO WEB SITE: WWW.LOCALIZASAT.COM</div>
<div class="topo">9. ÁREA DE ABRANGÊNCIA:</div>
<div><b>A)</b> A ÁREA DE COBERTURA DO RASTREAMENTO É A MESMA COBERTA PELA OPERADORA
DE TELEFONIA USADA NO RASTREADOR INSTALADO.</div>
<div><b>B)</b> EVENTUALMENTE PODERÃO OCORRER MODIFICAÇÕES NA ÁREA DE ABRANGÊNCIA, OU
SEJA, ALGUMAS ÁREAS DE COBERTURA PODERÃO SER EXCLUÍDAS OU INCLUÍDAS PELA
OPERADORA DE TELEFONIA CELULAR.</div>
<div class="topo">10. VIGÊNCIA E RESCISÃO DO CONTRATO:</div>
<div><b>A)</b> ESTE CONTRATO TERÁ DURAÇÃO MÍNIMA DE 12 MESES, PODENDO SER PRORROGADO
POR TEMPO INDETERMINADO APÓS ESTE PERÍODO.</div>
<div><b>B)</b> ESTE CONTRATO PODERÁ SER RESCINDIDO A QUALQUER MOMENTO APÓS O PERÍODO
DE CARÊNCIA MÍNIMA DE 12 MESES, POR QUAISQUER DAS PARTES, MEDIANTE
COMUNICAÇÃO POR ESCRITO COM ANTECEDÊNCIA DE 30 DIAS FICANDO O
CONTRATANTE OBRIGADO A ENTREGAR O RASTREADOR DADO EM COMODATO EM ATÉ
05(CINCO) DIAS ÚTEIS.</div>
<div><b>C)</b> QUANDO A RESCISÃO FOR MOTIVADA PELO CONTRATANTE, ANTES DE 12 MESES APÓS
A ASSINATURA DO PRESENTE, SERÁ COBRADO A TÍTULO DE MÃO DE OBRA PARA RETIRADA
DO RASTREADOR DADO EM COMODATO O VALOR DE R$ 100,00 E MULTA DE 50% DO
VALOR DA MENSALIDADE DOS MESES RESTANTES QUE COMPLETARIAM O PERÍODO DE
CARÊNCIA.</div>
<div class="topo">11. DO COMODATO (EMPRÉSTIMO DO EQUIPAMENTO RASTREADOR):</div>
<div><b>A)</b> A CONTRATADA EMPRESTARÁ, SOB REGIME DE COMODATO, AO CONTRATANTE, O
EQUIPAMENTO RASTREADOR DE SUA PROPRIEDADE A SER INSTALADO EM UM VEÍCULO
QUE SERÁ INDICADO PELA CONTRATANTE NO ATO DA ADESÃO E RATIFICADO COM
ASSINATURA DO RELATÓRIO DE SERVI ÇO NO DIA DA INSTALAÇÃO DO RASTREADOR.</div>
<div><b>B)</b> RESPONSABILIZA-SE O CONTRATANTE PELO USO ADEQUADO DO RASTREADOR QUE
ORA LHE É DADO EM COMODATO, BEM COMO POR MANTÊ-LO A SALVO DE PERDA,
FURTO, ROUBO, OU DANO POR MÁ UTILIZAÇÃO, OBRIGANDO-SE, POR FIM, A DEVOLVÊLOS 
EM PERFEITO ESTADO DE USO E CONSERVAÇÃO A CONTRATADA NA RESCISÃO DESTE
CONTRATO, EXCETUADOS OS DESGASTES NATURAIS DE TEMPO, USO, FURTO OU ROUBO
DO VEÍCULO; ESTA ÚLTIMA DESDE QUE APRESENTADO CÓPIA REPROGRÁFICA
DEVIDAMENTE AUTENTICADA DO BOLETIM DE OCORRÊNCIA REGISTRADO EM DELEGACIA
POLICIAL.</div>
<div><b>C)</b> A FALTA DE DEVOLUÇÃO FÍSICA DO RASTREADOR POR RESCISÃO DO PRESENTE
CONTRATO, EM ATÉ 5 DIAS ÚTEIS, NO ENDEREÇO DA CONTRATADA, IMPORTA NA
OBRIGAÇÃO DO CONTRATANTE PAGAR À CONTRATADA, IMEDIATAMENTE, O VALOR DE
R$350,00 (TREZENTOS E CINQUENTA REAIS) PARA CADA EQUIPAMENTO RASTREADOR.</div>
</div>
<div class="coluna_direita">
<div class="topo">12.DISPOSIÇÕES GERAIS FINAIS:</div>
<div><b>A)</b> O CONTRATO ORA ESTABELECIDO NÃO CONSTITUI E NÃO REPRESENTA, EM HIPÓTESE
ALGUMA, UMA APÓLICE DE SEGURO, NÃO HAVENDO E OU NÃO IMPLICANDO EM
QUALQUER COBERTURA OU INDENIZAÇÃO, DE QUALQUER NATUREZA, PARA A
CONTRATANTE, PARA OS USUÁRIOS DOS VEÍCULOS DE SUA FROTA E/OU TERCEIROS, OU
PARA OS PRÓPRIOS VEÍCULOS OU CARGAS, BEM COMO, NÃO SENDO GARANTIDA A
INFALIBILIDADE OU PROMETIDA PELA CONTRATADA A TOTAL SEGURANÇA E SUBTRAÇÃO
DO CARREGAMENTO OU PARTE, VEÍCULO OU PARTE DESTE, PASSAGEIROS, OBJETOS NO
INTERIOR, PEÇAS, ACESSÓRIOS E/OU A NÃO OCORRÊNCIA DOS DELITOS DE DESVIO DE
CARGA.</div>
<div><b>B)</b> CONTRATANTE E CONTRATADA AJUSTAM QUE A PARTE QUE MUDAR DE ENDEREÇO, SE
OBRIGA A INFORMAR A OUTRA, O NOVO ENDEREÇO.</div>
<div><b>C)</b> O CONTRATANTE DECLARA TER SIDO DEVIDAMENTE INSTRUÍDO PELA CONTRATADA
SOBRE O CORRETO FUNCIONAMENTO DO RASTREADOR E ACESSÓRIOS, SENDO
INFORMADO QUE O MANUAL DO USUÁRIO CONTENDO TODAS AS INFORMAÇÕES
NECESSÁRIAS À SUA OPERACIONALIZAÇÃO ENCONTRA-SE DISPONÍVEL NO ENDEREÇO DE
INTERNET.</div>
<div><b>D)</b> O INTEIRO TEOR DO PRESENTE CONTRATO ENCONTRA -SE DISPONÍVEL NO ENDEREÇO
DE INTERNTE DA CONTRATADA, PODENDO SER ACESSADO PELO CONTRATANTE A
QUALQUER MOMENTO.</div>
<div><b>E)</b> O E-MAIL DECLARADO PELA CONTRATANTE E QUALQUER E-MAIL DA CONTRATADA
COM FORMATO “sac@localizasat.com" SERÁ USADO PARA COMUNICAÇÃO FORMAL
E OFICIAL ENTRE AS PARTES.</div>
<div><b>F)</b> DÚVIDAS LIGAR PARA CENTRAL DE ATENDIMENTO: (83) 9764.2241 NO HORÁRIO
COMERCIAL</div>
<div class="topo">13. DO FORO:</div>
<div><b>A)</b> PARA DIRIMIR QUAISQUER CONTROVÉRSIAS ORIUNDAS DO PRESENTE CONTRATO, AS
PARTES ELEGEM O FORO DA COMARCA DE CAMPINA GRANDE/PB, INDEPENDENTEMENTE DE
QUALQUER OUTRA, POR MAIS PRIVILEGIADA QUE SEJA.
POR ESTAREM ASSIM JUSTOS E CONTRATADOS, FIRMAM O PRESENTE INSTRUMENTO, EM
DUAS VIAS DE IGUAL TEOR E FORMA.</div>

<div class="assinatura">
<img style="width: 350px ; height:auto" src="img/sign/{{$data->sign}}">
<p>LOCALIZASAT - RESPONSÁVEL</p>
<hr class="hr1">
</div>

<div class="assinatura">
<img style="width: 350px ; height:auto" src="img/sign/{{$data->sign}}">
<p>CLIENTE - {{$data->nome}}</p>
<hr class="hr1">
<p><?php
$DateAndTime = date('d.m.Y');  
echo "Campina Grande $DateAndTime";
?></p>
</div>

</div>
</body>

</html>